accent = "#84FFFF"
cursor = "#84FFFF"
foreground = "#A6ACCD"
background = "#0F111A"

selection_foreground = "#EEFFFF"
selection_background = "#1F2233"

color0 = "#090B10"
color1 = "#F07178"
color2 = "#C3E88D"
color3 = "#FFCB6B"
color4 = "#82AAFF"
color5 = "#C792EA"
color6 = "#89DDFF"
color7 = "#A6ACCD"

color8 = "#464B5D"
color9 = "#DC6068"
color10 = "#ABCF76"
color11 = "#E6B455"
color12 = "#6E98EB"
color13 = "#B480D6"
color14 = "#71C6E7"
color15 = "#EEFFFF"
